workloads:
  - name: "hpl"
    params:
      dir: "/home/ibiemond/sustainabench/scripts/snellius/cpu/genoa/configs/hpl/2nodes/" # Used to select cwd. Not used for locating the executable, only important for the .dat file.
      executable: "xhpl" # Full path to the executable. Does not do dir+executable, just executable