workloads:
  - name: "nvidia-stream"
    params:
      executable: "/home/ibd350/nvidia_hpc_benchmarks/cuda12/stream-gpu-test.sh"
      flags:
        - ["--n", "131072"] # On RTX A4000: Working set for FP64 = 3 × N × 8 bytes. 3 × 131072 × 8 ≈ 3.0 MB. Aim to fill just L2 Cache