workloads:
  - name: "vllm"
    params:
      args: [
        "--model", "Qwen/Qwen2.5-3B-Instruct",
        "--num-prompts", "8",
        "--input-len", "1024",
        "--output-len", "256",
      ]