metrics_dict:
  - unit: j
    sources:
      cpu_energy:
        priority: 100
        metrics:
          - kind: scalar
            path: energy.j
            contributes_to_total: true
            contribution_group: cpu_energy_j

      gpu_nv:
        priority: 100
        metrics:
          - kind: collection
            collection_path: "[:]"
            value_path: energy.j
            label_path: gpu_id
            contributes_to_total: true
            contribution_group: gpu_energy_j

      perf_energy:
        priority: 0
        metrics:
          - kind: scalar
            path: joules
            contributes_to_total: true
            contribution_group: cpu_energy_j

  - unit: kwh
    sources:
      cpu_energy:
        priority: 100
        metrics:
          - kind: scalar
            path: energy.kwh
            contributes_to_total: true
            contribution_group: cpu_energy_kwh

          - kind: collection
            collection_path: per_domain
            value_path: energy.kwh
            contributes_to_total: false
            contribution_group: null

      gpu_nv:
        priority: 100
        metrics:
          - kind: collection
            collection_path: "[:]"
            value_path: energy.kwh
            label_path: gpu_id
            contributes_to_total: true
            contribution_group: gpu_energy_kwh

      perf_energy:
        priority: 0
        metrics:
          - kind: scalar
            path: kwh
            contributes_to_total: true
            contribution_group: cpu_energy_kwh

  - unit: time
    sources:
      execution_time:
        priority: 100
        metrics:
          - kind: scalar
            path: "@"
            contributes_to_total: true
            contribution_group: execution_time

  - unit: max-execution-time
    sources:
      max_execution_time:
        priority: 0
        metrics:
          - kind: scalar
            path: "@"
            contributes_to_total: false
            contribution_group: null

  - unit: carbon
    sources:
      carbon:
        priority: 0
        metrics:
          - kind: scalar
            path: total_g
            contributes_to_total: true
            contribution_group: total_carbon

  - unit: all-carbon
    sources:
      all_carbon:
        priority: 0
        metrics:
          - kind: scalar
            path: g
            contributes_to_total: false
            contribution_group: null

  - unit: carbon-per-second
    sources:
      carbon_per_second:
        priority: 0
        metrics:
          - kind: scalar
            path: g
            contributes_to_total: false
            contribution_group: null

  - unit: energy-to-solution
    sources:
      energy_to_solution:
        priority: 0
        metrics:
          - kind: scalar
            path: j
            contributes_to_total: false
            contribution_group: null

  - unit: performance
    sources: # All sources: hpcg, hpl, stream, stress_ng; gpu_burn, nvidia_hpcg, nvidia_hpl, nvidia_stream, vllm
      stress_ng:
        priority: 0
        metrics:
          - kind: scalar
            path: "metrics.bogo_ops_per_sec_real"
            contributes_to_total: false
            contribution_group: null

      stream:
        priority: 0
        metrics:
          - kind: scalar
            path: 'Function."Copy:"."Best_Rate_MB/s"'
            contributes_to_total: false
            contribution_group: null

          - kind: scalar
            path: 'Function."Scale:"."Best_Rate_MB/s"'
            contributes_to_total: false
            contribution_group: null

          - kind: scalar
            path: 'Function."Add:"."Best_Rate_MB/s"'
            contributes_to_total: false
            contribution_group: null

          - kind: scalar
            path: 'Function."Triad:"."Best_Rate_MB/s"'
            contributes_to_total: false
            contribution_group: null
        

      hpl:
        priority: 0
        metrics:
          - kind: scalar
            path: "Gflops"
            contributes_to_total: false
            contribution_group: null
      
      hpcg:
        priority: 0
        metrics:
          - kind: scalar
            path: 'Final_Summary."HPCG_result_is_VALID_with_a_GFLOP/s_rating_of"'
            contributes_to_total: false
            contribution_group: null

      # -------------------------------

      gpu_burn: # Unknown rn; TODO: fix this
        priority: 0
        metrics:
          - kind: collection
            collection_path: "gpus"
            value_path: stats.gflops
            label_path: null
            contributes_to_total: false
            contribution_group: null

      nvidia_stream:
        priority: 0
        metrics:
          - kind: scalar
            path: 'Function."Copy:"."Rate_(MB/s)"'
            contributes_to_total: false
            contribution_group: null

          - kind: scalar
            path: 'Function."Scale:"."Rate_(MB/s)"'
            contributes_to_total: false
            contribution_group: null

          - kind: scalar
            path: 'Function."Add:"."Rate_(MB/s)"'
            contributes_to_total: false
            contribution_group: null

          - kind: scalar
            path: 'Function."Triad:"."Rate_(MB/s)"'
            contributes_to_total: false
            contribution_group: null

      nvidia_hpl:
        priority: 0
        metrics:
          - kind: scalar
            path: "Gflops"
            contributes_to_total: false
            contribution_group: null

          - kind: scalar
            path: "per_GPU"
            contributes_to_total: false
            contribution_group: null

      nvidia_hpcg:
        priority: 0
        metrics:
          - kind: scalar
            path: 'Final_Summary."HPCG_result_is_VALID_with_a_GFLOP/s_rating_of"'
            contributes_to_total: false
            contribution_group: null

      vllm:
        priority: 0
        metrics:
          - kind: scalar
            path: 'throughput."requests/s"'
            contributes_to_total: false
            contribution_group: null

          - kind: scalar
            path: 'throughput."total_tokens/s"'
            contributes_to_total: false
            contribution_group: null

          - kind: scalar
            path: 'throughput."output_tokens/s"'
            contributes_to_total: false
            contribution_group: null
