metrics_dict:
  - unit: j
    sources:
      cpu_energy:
        priority: 100
        metrics:
          - kind: scalar
            path: energy.j
            contributes_to_total: true
            contribution_group: cpu_energy_j

      gpu_nv:
        priority: 100
        metrics:
          - kind: collection
            collection_path: "[:]"
            value_path: energy.j
            label_path: gpu_id
            contributes_to_total: true
            contribution_group: gpu_energy_j

      perf_energy:
        priority: 0
        metrics:
          - kind: scalar
            path: joules
            contributes_to_total: true
            contribution_group: cpu_energy_j

  - unit: kwh
    sources:
      cpu_energy:
        priority: 100
        metrics:
          - kind: scalar
            path: energy.kwh
            contributes_to_total: true
            contribution_group: cpu_energy_kwh

          - kind: collection
            collection_path: per_domain
            value_path: energy.kwh
            contributes_to_total: false
            contribution_group: null

      gpu_nv:
        priority: 100
        metrics:
          - kind: collection
            collection_path: "[:]"
            value_path: energy.kwh
            label_path: gpu_id
            contributes_to_total: true
            contribution_group: gpu_energy_kwh

      perf_energy:
        priority: 0
        metrics:
          - kind: scalar
            path: kwh
            contributes_to_total: true
            contribution_group: cpu_energy_kwh

  - unit: time
    sources:
      execution_time:
        priority: 100
        metrics:
          - kind: scalar
            path: "."
            contributes_to_total: true
            contribution_group: execution_time
