workloads:
  - name: "nvidia-hpcg"
    params:
      executable: "/home/ibd350/nvidia_hpc_benchmarks/cuda12/hpcg.sh"
      flags:
        - ["--nx", "352"]
        - ["--ny", "352"]
        - ["--nz", "352"]
        - ["--rt", "600"]
