workloads:
  - name: "nvidia-hpcg"
    params:
      executable: "/home/ibiemond/nvidia_hpc_benchmarks/cuda12/hpcg.sh"
      flags:
        - ["--nx", "384"]
        - ["--ny", "384"]
        - ["--nz", "384"]
        - ["--rt", "300"]