workload:
  name: "hpl"
  params:
    dir: "path/to/hpl/" # Used to select cwd. Not used for locating the executable, only important for the .dat file.
    executable: "xhpl" # Full path to the executable. Does not do dir+executable, just executable
