workload:
  name: "nvidia-hpl"
  params:
    executable: "/home/ibd350/nvidia_hpc_benchmarks/cuda12/hpl.sh"
    flags:
      - ["--dat", "/home/ibd350/nvidia_hpc_benchmarks/cuda12/hpl-linux-x86_64/sample-dat/HPL-1GPU.dat"] # Arguments for the Nvidia HPL executable
