workload:
  name: "stress-ng"
  params:
    executable: "stress-ng" # Install via Conda/Mamba for easier installation than building by hand
    args: [
      "--cpu", "4",
      "--cpu-method", "matrixprod",
      "--timeout", "120s",
      # "--metrics-brief" # Does not need to be included since it is required by the parser anyways and the parser adds it always
    ]

