indicators:     # Top-level indicators object, must always exist
  indicatorA:   # For each indicator to configure through this file, define as 'indicators' sub-object. Name here must match indicator's object, as defined in the corresponding indicator file in 'sustainabench/indicators/'
    params:     # The parameters to configure per indicator. Has to be checked within each indicator's script.
      m: 1000
      n: 2000
      p: 5
  
  indicatorB:   # Example when supporting multiple indicators in a single config
    params:
      x: 5
      y: 10
      z: 15
