indicators:
  carbon:
    params:
      reference_time: 
        mode: fixed                     # 'fixed' to use 'value', 'auto' to select from most recent available date
        value: "2025-12-31T23:59:59Z"   # Date from when to count selected period back. Required ISO 8601 format.
      window:                           # How many years + months + days to slice from the selected parquet traces.
        years: 0
        months: 0
        days: 0
