workloads:
  - name: "hpcg"
    params:
      dir: "/home/ibd350/hpcg/build/bin/" # Used to select cwd. Not used for locating the executable, only important for the .dat file.
      executable: "/home/ibd350/hpcg/build/bin/xhpcg" # Full path to the executable. Does not do dir+executable, just executable
      args:
        - ["--nx", "384"]
        - ["--ny", "384"]
        - ["--nz", "384"]
        - ["--rt", "300"]