workloads:
  - name: "hpcg"
    params:
      dir: "/home/ibd350/sustainabench/scripts/das6/configs/workloads/hpcg/medium/" # Used to select cwd. Not used for locating the executable, only important for the .dat file.
      executable: "/home/ibd350/hpcg/build/bin/xhpcg" # Full path to the executable. Does not do dir+executable, just executable